services:

  # ==========================================
  # 1. BANCOS DE DADOS (Postgres & MongoDB)
  # ==========================================
  postgres:
    image: postgres:16-alpine
    container_name: poc-agenda-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: agendadb
    networks:
      - poc-network

  mongodb:
    image: mongo:latest
    container_name: poc-agenda-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    networks:
      - poc-network

  # ==========================================
  # 2. MENSAGERIA (Kafka & UI)
  # ==========================================
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: poc-agenda-kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - poc-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: poc-agenda-kafka-ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=PocAgenda-Cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    networks:
      - poc-network
    depends_on:
      - kafka

  # ==========================================
  # 3. OBSERVABILIDADE (Prometheus & Grafana)
  # ==========================================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - poc-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    # O Grafana (na poc-network) precisa do host-gateway para ler o Prometheus (no host)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - poc-network

networks:
  poc-network:
    driver: bridge
    ipam:
      config:
        # Forçamos a rede para uma faixa totalmente isolada!
        - subnet: 10.50.0.0/16
          gateway: 10.50.0.1