# (Opcional) Adiciona tags com o nome da aplicação para os gráficos
spring.application.name=poc-agenda-api

# Permite que o Tomcat aceite conexões de fora do localhost (ex: rede do Docker)
server.address=0.0.0.0

# ---------------------------------------------------------
# JPA / HIBERNATE
# ---------------------------------------------------------
# ---------------------------------------------------------
# BANCO DE DADOS (PostgreSQL)
# ---------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/agendadb
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto do Postgres explicitamente para o Hibernate não precisar "adivinhar"
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Desliga a autocriação de tabelas do Hibernate. Agora quem manda é o Flyway!
spring.jpa.hibernate.ddl-auto=validate

# Habilita o Flyway explicitamente
spring.flyway.enabled=true

# Exibe as consultas SQL no console para debugarmos a transação do Outbox depois
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Configuração de Mensageria (Local vs Cloud)
spring.kafka.bootstrap-servers=${KAFKA_SERVER:localhost:9092}

# Dinamismo de Segurança: O fallback padrão é PLAINTEXT (para o Docker local)
spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=PLAIN

# Adicionamos os fallbacks (:local) para não estourar erro no console
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="${KAFKA_USER:local}" \
    password="${KAFKA_PASSWORD:local}";

# Tópicos
app.kafka.topic.contact-events=${KAFKA_TOPIC:contact-events}

# Libera os endpoints de health, info e prometheus para acesso web
management.endpoints.web.exposure.include=health,info,prometheus

# (Opcional) Garante a exportação das métricas no novo padrão do Spring Boot 3
management.prometheus.metrics.export.enabled=true

# Força o Micrometer a enviar o nome da aplicação como uma tag reconhecida pelo Grafana
management.metrics.tags.application=${spring.application.name}