spring.application.name=agenda

# Configuração de Mensageria (Local vs Cloud)
spring.kafka.bootstrap-servers=${KAFKA_SERVER:localhost:9092}

# Dinamismo de Segurança: O fallback padrão é PLAINTEXT (para o Docker local)
spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=PLAIN

# Adicionamos os fallbacks (:local) para não estourar erro no console
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="${KAFKA_USER:local}" \
    password="${KAFKA_PASSWORD:local}";

# Tópicos
app.kafka.topic.contact-created=${KAFKA_TOPIC:contact-created}
app.kafka.topic.contact-deleted=${KAFKA_TOPIC_DELETED:contact-deleted}