spring.application.name=agenda

# Configuração de Mensageria Cloud - Confluent
spring.kafka.bootstrap-servers=${KAFKA_SERVER}
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="${KAFKA_USER}" \
    password="${KAFKA_PASSWORD}";

app.kafka.topic.contact-created=${KAFKA_TOPIC:contact-created}