name: Pipeline API Spring Boot

on:
  push:
    branches: [ "main" ]

jobs:
  # ==========================================
  # ESTÁGIO 1: Integração Contínua e Qualidade
  # ==========================================
  integration-and-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 21 Corretto
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Build e Análise SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=turisco-tech_poc-agenda-api -Dsonar.organization=turisco-tech -Dsonar.host.url=https://sonarcloud.io

  # ==========================================
  # ESTÁGIO 2: Geração e Entrega da Imagem
  # ==========================================
  delivery-and-container:
    needs: integration-and-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # Recriar o artefato (.jar) pois estamos em uma nova máquina
      - name: Setup Java 21 Corretto
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Gerar artefato (.jar)
        run: mvn clean package -DskipTests

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, e Push da Imagem
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: poc-agenda-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Tratamento de Erros e Logs Críticos
        if: failure()
        run: |
          echo "::error::Falha detectada na esteira! Coletando logs do ambiente de build..."
          docker system df
          docker ps -a
          echo "Exibindo os últimos eventos do sistema para diagnóstico:"
          dmesg | tail -n 20

  # ==========================================
  # ESTÁGIO 3: Deploy na AWS ECS
  # ==========================================
  deploy-to-aws:
    needs: delivery-and-container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código (para ler o task-definition.json)
        uses: actions/checkout@v4

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Fazemos o login no ECR novamente para pegar a URL do cofre dinamicamente e evitar falhas de variáveis
      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Preencher o novo ID da imagem e Variáveis na Task Definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/task-definition.json
          container-name: api-container
          image: ${{ steps.login-ecr.outputs.registry }}/poc-agenda-api:${{ github.sha }}
          environment-variables: |
            KAFKA_SERVER=${{ secrets.KAFKA_SERVER }}
            KAFKA_USER=${{ secrets.KAFKA_USER }}
            KAFKA_PASSWORD=${{ secrets.KAFKA_PASSWORD }}
            KAFKA_TOPIC=${{ secrets.KAFKA_TOPIC }}
            KAFKA_TOPIC_DELETED=${{ secrets.KAFKA_TOPIC_DELETED }}

      - name: Deploy da nova Task Definition no Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: poc-agenda-api-service
          cluster: poc-agenda-cluster
          wait-for-service-stability: true